// Line icons offered in the Keystatic editor (Tabler Icons, MIT, via @iconify-json/tabler).
// To add one, find its name at https://tabler.io/icons and append it here with a Czech label.
export const ICONS = [
  { value: 'flame', label: 'Plamen (hoří)' },
  { value: 'alert-triangle', label: 'Varování' },
  { value: 'history', label: 'Historie' },
  { value: 'repeat', label: 'Opakování' },
  { value: 'hourglass', label: 'Přesýpací hodiny' },
  { value: 'clock', label: 'Hodiny' },
  { value: 'files', label: 'Soubory' },
  { value: 'file-text', label: 'Dokument' },
  { value: 'clipboard-list', label: 'Seznam' },
  { value: 'checklist', label: 'Kontrolní seznam' },
  { value: 'zoom-check', label: 'Lupa (audit)' },
  { value: 'settings-automation', label: 'Automatizace' },
  { value: 'route', label: 'Proces / cesta' },
  { value: 'git-branch', label: 'Větvení procesu' },
  { value: 'puzzle', label: 'Puzzle' },
  { value: 'brain', label: 'Mozek (AI)' },
  { value: 'robot', label: 'Robot' },
  { value: 'sparkles', label: 'Jiskry (AI)' },
  { value: 'message-chatbot', label: 'Chatbot' },
  { value: 'messages', label: 'Konverzace' },
  { value: 'mail', label: 'E-mail' },
  { value: 'phone', label: 'Telefon' },
  { value: 'writing', label: 'Psaní' },
  { value: 'database', label: 'Databáze' },
  { value: 'cloud', label: 'Cloud' },
  { value: 'device-laptop', label: 'Notebook' },
  { value: 'shield-check', label: 'Bezpečnost' },
  { value: 'lock', label: 'Zámek' },
  { value: 'chart-bar', label: 'Graf' },
  { value: 'chart-line', label: 'Graf vývoje' },
  { value: 'trending-up', label: 'Růst' },
  { value: 'coin', label: 'Peníze' },
  { value: 'target', label: 'Cíl' },
  { value: 'bulb', label: 'Žárovka (nápad)' },
  { value: 'rocket', label: 'Raketa' },
  { value: 'calendar', label: 'Kalendář' },
  { value: 'briefcase', label: 'Kufřík' },
  { value: 'building', label: 'Firma' },
  { value: 'building-bank', label: 'Univerzita / instituce' },
  { value: 'school', label: 'Škola' },
  { value: 'presentation', label: 'Prezentace' },
  { value: 'certificate', label: 'Certifikát' },
  { value: 'book', label: 'Kniha' },
  { value: 'user', label: 'Člověk' },
  { value: 'users', label: 'Lidé' },
  { value: 'users-group', label: 'Skupina lidí' },
  { value: 'heart-handshake', label: 'Spolupráce' },
] as const;

export type IconName = (typeof ICONS)[number]['value'];
export const ICON_NAMES = ICONS.map((i) => i.value);
